INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "../ritm_interactive_segmentation/datasets/GrabCut"
BERKELEY_PATH: "../ritm_interactive_segmentation/datasets/Berkeley"
DAVIS_PATH: "../ritm_interactive_segmentation/datasets/DAVIS"
COCO_MVAL_PATH: "../ritm_interactive_segmentation/datasets/COCO_MVal"












